// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package msg

// Injectors from wire.go:

// InitializeEvent creates an Event. It will error if the Event is staffed with
// a grumpy greeter.
func InitializeEvent(phrase string) (*Event, error) {
	message := NewMessage(phrase)
	greeter := NewGreeter(message)
	event := &Event{
		Greeter: greeter,
	}
	return event, nil
}
