// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitA() (A, error) {
	b := &B{}
	a := A{
		is: b,
	}
	return a, nil
}

// wire.go:

var SuperSet = wire.NewSet(wire.Struct(new(B), "*"), wire.Struct(new(A), "*"), wire.Bind(new(IServer), new(*B)))
